// Copyright (C) 2026 Ben Grimm. Licensed under AGPL-3.0 (https://www.gnu.org/licenses/agpl-3.0.txt)

// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package programs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type DhcpSocketDhcpAckInfo struct {
	_             structs.HostLayout
	YourIp        uint32
	ServerIp      uint32
	SubnetMask    uint32
	Router        uint32
	DnsServers    [4]uint32
	LeaseTime     uint32
	RenewalTime   uint32
	RebindingTime uint32
	PacketSize    uint16
	_             [2]byte
	Timestamp     uint64
}

type DhcpSocketDhcpDiscoverInfo struct {
	_              structs.HostLayout
	MacAddr        [6]uint8
	HostnameLen    uint8
	Hostname       [64]int8
	VendorClassLen uint8
	VendorClass    [64]int8
	PacketSize     uint16
	_              [6]byte
	Timestamp      uint64
}

type DhcpSocketDhcpKey struct {
	_       structs.HostLayout
	Xid     uint32
	MacAddr [6]uint8
	Pad     uint16
}

type DhcpSocketDhcpOfferInfo struct {
	_          structs.HostLayout
	YourIp     uint32
	ServerIp   uint32
	SubnetMask uint32
	Router     uint32
	DnsServers [4]uint32
	LeaseTime  uint32
	PacketSize uint16
	_          [2]byte
	Timestamp  uint64
}

type DhcpSocketDhcpRequestInfo struct {
	_           structs.HostLayout
	MacAddr     [6]uint8
	_           [2]byte
	RequestedIp uint32
	ServerIp    uint32
	HostnameLen uint8
	Hostname    [64]int8
	_           [1]byte
	PacketSize  uint16
	_           [4]byte
	Timestamp   uint64
}

// LoadDhcpSocket returns the embedded CollectionSpec for DhcpSocket.
func LoadDhcpSocket() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DhcpSocketBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load DhcpSocket: %w", err)
	}

	return spec, err
}

// LoadDhcpSocketObjects loads DhcpSocket and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*DhcpSocketObjects
//	*DhcpSocketPrograms
//	*DhcpSocketMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadDhcpSocketObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadDhcpSocket()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// DhcpSocketSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DhcpSocketSpecs struct {
	DhcpSocketProgramSpecs
	DhcpSocketMapSpecs
	DhcpSocketVariableSpecs
}

// DhcpSocketProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DhcpSocketProgramSpecs struct {
	DhcpSocketFilter *ebpf.ProgramSpec `ebpf:"dhcp_socket_filter"`
}

// DhcpSocketMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DhcpSocketMapSpecs struct {
	DhcpAcks      *ebpf.MapSpec `ebpf:"dhcp_acks"`
	DhcpDiscovers *ebpf.MapSpec `ebpf:"dhcp_discovers"`
	DhcpEvents    *ebpf.MapSpec `ebpf:"dhcp_events"`
	DhcpOffers    *ebpf.MapSpec `ebpf:"dhcp_offers"`
	DhcpRequests  *ebpf.MapSpec `ebpf:"dhcp_requests"`
	DhcpStats     *ebpf.MapSpec `ebpf:"dhcp_stats"`
}

// DhcpSocketVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DhcpSocketVariableSpecs struct {
}

// DhcpSocketObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadDhcpSocketObjects or ebpf.CollectionSpec.LoadAndAssign.
type DhcpSocketObjects struct {
	DhcpSocketPrograms
	DhcpSocketMaps
	DhcpSocketVariables
}

func (o *DhcpSocketObjects) Close() error {
	return _DhcpSocketClose(
		&o.DhcpSocketPrograms,
		&o.DhcpSocketMaps,
	)
}

// DhcpSocketMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadDhcpSocketObjects or ebpf.CollectionSpec.LoadAndAssign.
type DhcpSocketMaps struct {
	DhcpAcks      *ebpf.Map `ebpf:"dhcp_acks"`
	DhcpDiscovers *ebpf.Map `ebpf:"dhcp_discovers"`
	DhcpEvents    *ebpf.Map `ebpf:"dhcp_events"`
	DhcpOffers    *ebpf.Map `ebpf:"dhcp_offers"`
	DhcpRequests  *ebpf.Map `ebpf:"dhcp_requests"`
	DhcpStats     *ebpf.Map `ebpf:"dhcp_stats"`
}

func (m *DhcpSocketMaps) Close() error {
	return _DhcpSocketClose(
		m.DhcpAcks,
		m.DhcpDiscovers,
		m.DhcpEvents,
		m.DhcpOffers,
		m.DhcpRequests,
		m.DhcpStats,
	)
}

// DhcpSocketVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadDhcpSocketObjects or ebpf.CollectionSpec.LoadAndAssign.
type DhcpSocketVariables struct {
}

// DhcpSocketPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadDhcpSocketObjects or ebpf.CollectionSpec.LoadAndAssign.
type DhcpSocketPrograms struct {
	DhcpSocketFilter *ebpf.Program `ebpf:"dhcp_socket_filter"`
}

func (p *DhcpSocketPrograms) Close() error {
	return _DhcpSocketClose(
		p.DhcpSocketFilter,
	)
}

func _DhcpSocketClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dhcpsocket_bpfel.o
var _DhcpSocketBytes []byte
