// Copyright (C) 2026 Ben Grimm. Licensed under AGPL-3.0 (https://www.gnu.org/licenses/agpl-3.0.txt)

// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package programs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type DnsSocketDnsKey struct {
	_       structs.HostLayout
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	QueryId uint16
	Pad     uint16
}

type DnsSocketDnsQueryInfo struct {
	_          structs.HostLayout
	QueryType  uint16
	QueryClass uint16
	Domain     [253]int8
	_          [1]byte
	PacketSize uint16
	_          [4]byte
	Timestamp  uint64
}

type DnsSocketDnsResponseInfo struct {
	_                 structs.HostLayout
	ResponseCode      uint8
	_                 [1]byte
	AnswerCount       uint16
	AuthorityCount    uint16
	AdditionalCount   uint16
	QueryTimestamp    uint64
	ResponseTimestamp uint64
	Domain            [253]int8
	_                 [1]byte
	PacketSize        uint16
}

// LoadDnsSocket returns the embedded CollectionSpec for DnsSocket.
func LoadDnsSocket() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DnsSocketBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load DnsSocket: %w", err)
	}

	return spec, err
}

// LoadDnsSocketObjects loads DnsSocket and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*DnsSocketObjects
//	*DnsSocketPrograms
//	*DnsSocketMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadDnsSocketObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadDnsSocket()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// DnsSocketSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsSocketSpecs struct {
	DnsSocketProgramSpecs
	DnsSocketMapSpecs
	DnsSocketVariableSpecs
}

// DnsSocketProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsSocketProgramSpecs struct {
	DnsSocketFilter *ebpf.ProgramSpec `ebpf:"dns_socket_filter"`
}

// DnsSocketMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsSocketMapSpecs struct {
	DnsEvents    *ebpf.MapSpec `ebpf:"dns_events"`
	DnsQueries   *ebpf.MapSpec `ebpf:"dns_queries"`
	DnsResponses *ebpf.MapSpec `ebpf:"dns_responses"`
	DnsStats     *ebpf.MapSpec `ebpf:"dns_stats"`
}

// DnsSocketVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsSocketVariableSpecs struct {
}

// DnsSocketObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadDnsSocketObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsSocketObjects struct {
	DnsSocketPrograms
	DnsSocketMaps
	DnsSocketVariables
}

func (o *DnsSocketObjects) Close() error {
	return _DnsSocketClose(
		&o.DnsSocketPrograms,
		&o.DnsSocketMaps,
	)
}

// DnsSocketMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadDnsSocketObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsSocketMaps struct {
	DnsEvents    *ebpf.Map `ebpf:"dns_events"`
	DnsQueries   *ebpf.Map `ebpf:"dns_queries"`
	DnsResponses *ebpf.Map `ebpf:"dns_responses"`
	DnsStats     *ebpf.Map `ebpf:"dns_stats"`
}

func (m *DnsSocketMaps) Close() error {
	return _DnsSocketClose(
		m.DnsEvents,
		m.DnsQueries,
		m.DnsResponses,
		m.DnsStats,
	)
}

// DnsSocketVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadDnsSocketObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsSocketVariables struct {
}

// DnsSocketPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadDnsSocketObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsSocketPrograms struct {
	DnsSocketFilter *ebpf.Program `ebpf:"dns_socket_filter"`
}

func (p *DnsSocketPrograms) Close() error {
	return _DnsSocketClose(
		p.DnsSocketFilter,
	)
}

func _DnsSocketClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dnssocket_bpfel.o
var _DnsSocketBytes []byte
