// Copyright (C) 2026 Ben Grimm. Licensed under AGPL-3.0 (https://www.gnu.org/licenses/agpl-3.0.txt)

// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package programs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TcOffloadFlowKey struct {
	_       structs.HostLayout
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	IpProto uint8
	_       [3]byte
	Ifindex uint32
	Padding [3]uint8
	_       [1]byte
}

type TcOffloadFlowState struct {
	_           structs.HostLayout
	FirstSeen   uint64
	LastSeen    uint64
	PacketCount uint64
	ByteCount   uint64
	Verdict     uint32
	OffloadMark uint32
	QosProfile  uint32
	Flags       uint8
	Padding     [3]uint8
}

type TcOffloadQosProfile struct {
	_          structs.HostLayout
	RateLimit  uint32
	BurstLimit uint32
	Priority   uint8
	AppClass   uint8
	Padding    [2]uint8
}

type TcOffloadTcStats struct {
	_                structs.HostLayout
	PacketsProcessed uint64
	PacketsFastPath  uint64
	PacketsSlowPath  uint64
	PacketsDropped   uint64
	BytesProcessed   uint64
}

// LoadTcOffload returns the embedded CollectionSpec for TcOffload.
func LoadTcOffload() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcOffloadBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcOffload: %w", err)
	}

	return spec, err
}

// LoadTcOffloadObjects loads TcOffload and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcOffloadObjects
//	*TcOffloadPrograms
//	*TcOffloadMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcOffloadObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcOffload()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcOffloadSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcOffloadSpecs struct {
	TcOffloadProgramSpecs
	TcOffloadMapSpecs
	TcOffloadVariableSpecs
}

// TcOffloadProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcOffloadProgramSpecs struct {
	TcEgressFastPath *ebpf.ProgramSpec `ebpf:"tc_egress_fast_path"`
	TcFastPath       *ebpf.ProgramSpec `ebpf:"tc_fast_path"`
}

// TcOffloadMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcOffloadMapSpecs struct {
	FlowMap     *ebpf.MapSpec `ebpf:"flow_map"`
	QosProfiles *ebpf.MapSpec `ebpf:"qos_profiles"`
	TcStatsMap  *ebpf.MapSpec `ebpf:"tc_stats_map"`
}

// TcOffloadVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcOffloadVariableSpecs struct {
}

// TcOffloadObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcOffloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcOffloadObjects struct {
	TcOffloadPrograms
	TcOffloadMaps
	TcOffloadVariables
}

func (o *TcOffloadObjects) Close() error {
	return _TcOffloadClose(
		&o.TcOffloadPrograms,
		&o.TcOffloadMaps,
	)
}

// TcOffloadMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcOffloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcOffloadMaps struct {
	FlowMap     *ebpf.Map `ebpf:"flow_map"`
	QosProfiles *ebpf.Map `ebpf:"qos_profiles"`
	TcStatsMap  *ebpf.Map `ebpf:"tc_stats_map"`
}

func (m *TcOffloadMaps) Close() error {
	return _TcOffloadClose(
		m.FlowMap,
		m.QosProfiles,
		m.TcStatsMap,
	)
}

// TcOffloadVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTcOffloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcOffloadVariables struct {
}

// TcOffloadPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcOffloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcOffloadPrograms struct {
	TcEgressFastPath *ebpf.Program `ebpf:"tc_egress_fast_path"`
	TcFastPath       *ebpf.Program `ebpf:"tc_fast_path"`
}

func (p *TcOffloadPrograms) Close() error {
	return _TcOffloadClose(
		p.TcEgressFastPath,
		p.TcFastPath,
	)
}

func _TcOffloadClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcoffload_bpfel.o
var _TcOffloadBytes []byte
