/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */
/* This file is auto-generated by bpftool */
#ifndef __VMLINUX_H__
#define __VMLINUX_H__

/* This is a placeholder vmlinux.h for development.
 * In the VM, this will be generated with:
 * bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
 */

#ifndef __VMLINUX_H__
#warning "Using placeholder vmlinux.h. Run 'make vmlinux.h' in VM to generate proper header."
#endif

/* Minimal type definitions for compilation */
typedef unsigned char __u8;
typedef unsigned short __u16;
typedef unsigned int __u32;
typedef unsigned long long __u64;

typedef signed char __s8;
typedef short __s16;
typedef int __s32;
typedef long long __s64;

typedef __u8 u8;
typedef __u16 u16;
typedef __u32 u32;
typedef __u64 u64;

typedef __u16 __le16;
typedef __u16 __be16;
typedef __u32 __le32;
typedef __u32 __be32;
typedef __u64 __le64;
typedef __u64 __be64;

typedef __u16 __sum16;
typedef __u32 __sum;

/* NULL definition */
#ifndef NULL
#define NULL ((void *)0)
#endif

/* Inline attribute */
#define __always_inline inline __attribute__((always_inline))

/* BPF helper functions */
static __always_inline __u64 bpf_get_current_pid_tgid(void) {
    return 0;
}

static __always_inline __u16 bpf_ntohs(__u16 val) {
    return __builtin_bswap16(val);
}

static __always_inline __u16 __bpf_constant_htons(__u16 val) {
    return __builtin_bswap16(val);
}

static __always_inline void *bpf_map_lookup_elem(void *map, const void *key) {
    return NULL;
}

static __always_inline long bpf_map_update_elem(void *map, const void *key, const void *value, unsigned long flags) {
    return 0;
}

static __always_inline long bpf_map_delete_elem(void *map, const void *key) {
    return 0;
}

static __always_inline __u64 bpf_ktime_get_ns(void) {
    return 0;
}

static __always_inline long bpf_probe_read_kernel(void *dst, __u32 size, const void *unsafe_ptr) {
    return 0;
}

/* IPv6 address structure */
struct in6_addr {
	union {
		__u8 u6_addr8[16];
		__be16 u6_addr16[8];
		__be32 u6_addr32[4];
	} in6_u;
#define s6_addr		in6_u.u6_addr8
#define s6_addr16	in6_u.u6_addr16
#define s6_addr32	in6_u.u6_addr32
};

/* Basic network structures */
struct ethhdr {
	unsigned char h_dest[6];
	unsigned char h_source[6];
	__be16 h_proto;
};

struct iphdr {
	__u8 ihl:4;
	__u8 version:4;
	__u8 tos;
	__be16 tot_len;
	__be16 id;
	__be16 frag_off;
	__u8 ttl;
	__u8 protocol;
	__sum check;
	__be32 saddr;
	__be32 daddr;
};

struct ipv6hdr {
	__u8 priority:4;
	__u8 version:4;
	__u8 flow_lbl[3];
	__be16 payload_len;
	__u8 nexthdr;
	__u8 hop_limit;
	struct in6_addr saddr;
	struct in6_addr daddr;
};

struct tcphdr {
	__be16 source;
	__be16 dest;
	__be32 seq;
	__be32 ack_seq;
	__u16 res1:4;
	__u16 doff:4;
	__u16 fin:1;
	__u16 syn:1;
	__u16 rst:1;
	__u16 psh:1;
	__u16 ack:1;
	__u16 urg:1;
	__u16 ece:1;
	__u16 cwr:1;
	__be16 window;
	__sum check;
	__be16 urg_ptr;
};

struct udphdr {
	__be16 source;
	__be16 dest;
	__be16 len;
	__sum check;
};

/* eBPF sk_buff structure */
struct __sk_buff {
	__u32 len;
	__u32 pkt_type;
	__u32 hash;
	__u32 queue_mapping;
	__u32 protocol;
	__u32 vlan_present;
	__u32 vlan_tci;
	__u32 vlan_proto;
	__u32 priority;
	__u32 ingress_ifindex;
	__u32 ifindex;
	__u32 tc_index;
	__u32 cb[5];
	__u32 tc_classid;
	__u32 data;
	__u32 data_end;
	__u32 data_meta;
	__u32 flow_keys;
	__u32 mark;
	__u32 gso_segs;
};

/* XDP context structure */
struct xdp_md {
	__u32 data;
	__u32 data_end;
	__u32 data_meta;
	__u32 ingress_ifindex;
	__u32 rx_queue_index;
};

/* libbpf pinning constants */
#define LIBBPF_PIN_BY_NAME 1

/* Basic constants */
#define ETH_P_IP	0x0800
#define ETH_P_IPV6	0x86DD
#define ETH_P_ARP	0x0806
#define IPPROTO_TCP	6
#define IPPROTO_UDP	17
#define IPPROTO_ICMP	1
#define IPPROTO_ICMPV6	58

#endif /* __VMLINUX_H__ */
