// Copyright (C) 2026 Ben Grimm. Licensed under AGPL-3.0 (https://www.gnu.org/licenses/agpl-3.0.txt)

// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package programs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type XdpBlocklistFlowKey struct {
	_       structs.HostLayout
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	IpProto uint8
	_       [3]byte
	Ifindex uint32
	Padding [3]uint8
	_       [1]byte
}

type XdpBlocklistFlowState struct {
	_           structs.HostLayout
	FirstSeen   uint64
	LastSeen    uint64
	PacketCount uint64
	ByteCount   uint64
	Verdict     uint32
	OffloadMark uint32
	QosProfile  uint32
	Flags       uint8
	Padding     [3]uint8
}

type XdpBlocklistStatistics struct {
	_                structs.HostLayout
	PacketsProcessed uint64
	PacketsDropped   uint64
	PacketsPassed    uint64
	BytesProcessed   uint64
	BlockedIps       uint64
	BlockedDns       uint64
	FlowsOffloaded   uint64
}

// LoadXdpBlocklist returns the embedded CollectionSpec for XdpBlocklist.
func LoadXdpBlocklist() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpBlocklistBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load XdpBlocklist: %w", err)
	}

	return spec, err
}

// LoadXdpBlocklistObjects loads XdpBlocklist and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*XdpBlocklistObjects
//	*XdpBlocklistPrograms
//	*XdpBlocklistMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadXdpBlocklistObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadXdpBlocklist()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// XdpBlocklistSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpBlocklistSpecs struct {
	XdpBlocklistProgramSpecs
	XdpBlocklistMapSpecs
	XdpBlocklistVariableSpecs
}

// XdpBlocklistProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpBlocklistProgramSpecs struct {
	XdpBlocklistProg *ebpf.ProgramSpec `ebpf:"xdp_blocklist_prog"`
}

// XdpBlocklistMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpBlocklistMapSpecs struct {
	Config      *ebpf.MapSpec `ebpf:"config"`
	DnsBloom    *ebpf.MapSpec `ebpf:"dns_bloom"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	FlowMap     *ebpf.MapSpec `ebpf:"flow_map"`
	IpBlocklist *ebpf.MapSpec `ebpf:"ip_blocklist"`
	Statistics  *ebpf.MapSpec `ebpf:"statistics"`
}

// XdpBlocklistVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpBlocklistVariableSpecs struct {
}

// XdpBlocklistObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadXdpBlocklistObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpBlocklistObjects struct {
	XdpBlocklistPrograms
	XdpBlocklistMaps
	XdpBlocklistVariables
}

func (o *XdpBlocklistObjects) Close() error {
	return _XdpBlocklistClose(
		&o.XdpBlocklistPrograms,
		&o.XdpBlocklistMaps,
	)
}

// XdpBlocklistMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadXdpBlocklistObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpBlocklistMaps struct {
	Config      *ebpf.Map `ebpf:"config"`
	DnsBloom    *ebpf.Map `ebpf:"dns_bloom"`
	Events      *ebpf.Map `ebpf:"events"`
	FlowMap     *ebpf.Map `ebpf:"flow_map"`
	IpBlocklist *ebpf.Map `ebpf:"ip_blocklist"`
	Statistics  *ebpf.Map `ebpf:"statistics"`
}

func (m *XdpBlocklistMaps) Close() error {
	return _XdpBlocklistClose(
		m.Config,
		m.DnsBloom,
		m.Events,
		m.FlowMap,
		m.IpBlocklist,
		m.Statistics,
	)
}

// XdpBlocklistVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadXdpBlocklistObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpBlocklistVariables struct {
}

// XdpBlocklistPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadXdpBlocklistObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpBlocklistPrograms struct {
	XdpBlocklistProg *ebpf.Program `ebpf:"xdp_blocklist_prog"`
}

func (p *XdpBlocklistPrograms) Close() error {
	return _XdpBlocklistClose(
		p.XdpBlocklistProg,
	)
}

func _XdpBlocklistClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpblocklist_bpfel.o
var _XdpBlocklistBytes []byte
