// Copyright (C) 2026 Ben Grimm. Licensed under AGPL-3.0 (https://www.gnu.org/licenses/agpl-3.0.txt)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: device.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ClaimCode     string                 `protobuf:"bytes,2,opt,name=claim_code,json=claimCode,proto3" json:"claim_code,omitempty"`
	Csr           []byte                 `protobuf:"bytes,3,opt,name=csr,proto3" json:"csr,omitempty"`                                 // PKCS#10 CSR
	DeviceInfo    string                 `protobuf:"bytes,4,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"` // JSON: hostname, version, interfaces
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *EnrollRequest) GetClaimCode() string {
	if x != nil {
		return x.ClaimCode
	}
	return ""
}

func (x *EnrollRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

func (x *EnrollRequest) GetDeviceInfo() string {
	if x != nil {
		return x.DeviceInfo
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   []byte                 `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`                          // PEM-encoded device cert
	CaCertificate []byte                 `protobuf:"bytes,2,opt,name=ca_certificate,json=caCertificate,proto3" json:"ca_certificate,omitempty"` // PEM-encoded CA cert
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	OrgName       string                 `protobuf:"bytes,4,opt,name=org_name,json=orgName,proto3" json:"org_name,omitempty"`
	PrivateKey    []byte                 `protobuf:"bytes,5,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *EnrollResponse) GetCaCertificate() []byte {
	if x != nil {
		return x.CaCertificate
	}
	return nil
}

func (x *EnrollResponse) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *EnrollResponse) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

func (x *EnrollResponse) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Telemetry
	//	*AgentMessage_ConfigAck
	//	*AgentMessage_Alert
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetTelemetry() *TelemetryBatch {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Telemetry); ok {
			return x.Telemetry
		}
	}
	return nil
}

func (x *AgentMessage) GetConfigAck() *ConfigAck {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ConfigAck); ok {
			return x.ConfigAck
		}
	}
	return nil
}

func (x *AgentMessage) GetAlert() *Alert {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Alert); ok {
			return x.Alert
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Telemetry struct {
	Telemetry *TelemetryBatch `protobuf:"bytes,2,opt,name=telemetry,proto3,oneof"`
}

type AgentMessage_ConfigAck struct {
	ConfigAck *ConfigAck `protobuf:"bytes,3,opt,name=config_ack,json=configAck,proto3,oneof"`
}

type AgentMessage_Alert struct {
	Alert *Alert `protobuf:"bytes,4,opt,name=alert,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_Telemetry) isAgentMessage_Payload() {}

func (*AgentMessage_ConfigAck) isAgentMessage_Payload() {}

func (*AgentMessage_Alert) isAgentMessage_Payload() {}

type CloudMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CloudMessage_Config
	//	*CloudMessage_Command
	//	*CloudMessage_CertRenewal
	Payload       isCloudMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudMessage) Reset() {
	*x = CloudMessage{}
	mi := &file_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudMessage) ProtoMessage() {}

func (x *CloudMessage) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudMessage.ProtoReflect.Descriptor instead.
func (*CloudMessage) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{3}
}

func (x *CloudMessage) GetPayload() isCloudMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CloudMessage) GetConfig() *ConfigIntent {
	if x != nil {
		if x, ok := x.Payload.(*CloudMessage_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *CloudMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*CloudMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *CloudMessage) GetCertRenewal() *CertificateRenewal {
	if x != nil {
		if x, ok := x.Payload.(*CloudMessage_CertRenewal); ok {
			return x.CertRenewal
		}
	}
	return nil
}

type isCloudMessage_Payload interface {
	isCloudMessage_Payload()
}

type CloudMessage_Config struct {
	Config *ConfigIntent `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type CloudMessage_Command struct {
	Command *Command `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

type CloudMessage_CertRenewal struct {
	CertRenewal *CertificateRenewal `protobuf:"bytes,3,opt,name=cert_renewal,json=certRenewal,proto3,oneof"`
}

func (*CloudMessage_Config) isCloudMessage_Payload() {}

func (*CloudMessage_Command) isCloudMessage_Payload() {}

func (*CloudMessage_CertRenewal) isCloudMessage_Payload() {}

type ConfigIntent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ConfigHcl     []byte                 `protobuf:"bytes,2,opt,name=config_hcl,json=configHcl,proto3" json:"config_hcl,omitempty"`       // Full or partial HCL
	MergeFields   []string               `protobuf:"bytes,3,rep,name=merge_fields,json=mergeFields,proto3" json:"merge_fields,omitempty"` // Fields to merge vs replace
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigIntent) Reset() {
	*x = ConfigIntent{}
	mi := &file_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigIntent) ProtoMessage() {}

func (x *ConfigIntent) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigIntent.ProtoReflect.Descriptor instead.
func (*ConfigIntent) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigIntent) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigIntent) GetConfigHcl() []byte {
	if x != nil {
		return x.ConfigHcl
	}
	return nil
}

func (x *ConfigIntent) GetMergeFields() []string {
	if x != nil {
		return x.MergeFields
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "degraded", "error"
	ConfigVersion int64                  `protobuf:"varint,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Heartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Heartbeat) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

type TelemetryBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TelemetryEvent      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_device_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{6}
}

func (x *TelemetryBatch) GetEvents() []*TelemetryEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type TelemetryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_device_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{7}
}

func (x *TelemetryEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TelemetryEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TelemetryEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ConfigAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigAck) Reset() {
	*x = ConfigAck{}
	mi := &file_device_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigAck) ProtoMessage() {}

func (x *ConfigAck) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigAck.ProtoReflect.Descriptor instead.
func (*ConfigAck) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigAck) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"` // "info", "warning", "critical"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_device_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{9}
}

func (x *Alert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "ping", "traceroute", "reboot", "debug"
	Args          map[string]string      `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_device_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{10}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Command) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

type CertificateRenewal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   []byte                 `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateRenewal) Reset() {
	*x = CertificateRenewal{}
	mi := &file_device_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateRenewal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRenewal) ProtoMessage() {}

func (x *CertificateRenewal) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRenewal.ProtoReflect.Descriptor instead.
func (*CertificateRenewal) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{11}
}

func (x *CertificateRenewal) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type GetConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	CurrentVersion int64                  `protobuf:"varint,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_device_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{12}
}

func (x *GetConfigRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetConfigRequest) GetCurrentVersion() int64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ConfigIntent          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	UpToDate      bool                   `protobuf:"varint,2,opt,name=up_to_date,json=upToDate,proto3" json:"up_to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_device_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{13}
}

func (x *GetConfigResponse) GetConfig() *ConfigIntent {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetConfigResponse) GetUpToDate() bool {
	if x != nil {
		return x.UpToDate
	}
	return false
}

var File_device_proto protoreflect.FileDescriptor

const file_device_proto_rawDesc = "" +
	"\n" +
	"\fdevice.proto\x12\rflywall.cloud\"~\n" +
	"\rEnrollRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"claim_code\x18\x02 \x01(\tR\tclaimCode\x12\x10\n" +
	"\x03csr\x18\x03 \x01(\fR\x03csr\x12\x1f\n" +
	"\vdevice_info\x18\x04 \x01(\tR\n" +
	"deviceInfo\"\xac\x01\n" +
	"\x0eEnrollResponse\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\x12%\n" +
	"\x0eca_certificate\x18\x02 \x01(\fR\rcaCertificate\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x19\n" +
	"\borg_name\x18\x04 \x01(\tR\aorgName\x12\x1f\n" +
	"\vprivate_key\x18\x05 \x01(\fR\n" +
	"privateKey\"\xfb\x01\n" +
	"\fAgentMessage\x128\n" +
	"\theartbeat\x18\x01 \x01(\v2\x18.flywall.cloud.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\ttelemetry\x18\x02 \x01(\v2\x1d.flywall.cloud.TelemetryBatchH\x00R\ttelemetry\x129\n" +
	"\n" +
	"config_ack\x18\x03 \x01(\v2\x18.flywall.cloud.ConfigAckH\x00R\tconfigAck\x12,\n" +
	"\x05alert\x18\x04 \x01(\v2\x14.flywall.cloud.AlertH\x00R\x05alertB\t\n" +
	"\apayload\"\xcc\x01\n" +
	"\fCloudMessage\x125\n" +
	"\x06config\x18\x01 \x01(\v2\x1b.flywall.cloud.ConfigIntentH\x00R\x06config\x122\n" +
	"\acommand\x18\x02 \x01(\v2\x16.flywall.cloud.CommandH\x00R\acommand\x12F\n" +
	"\fcert_renewal\x18\x03 \x01(\v2!.flywall.cloud.CertificateRenewalH\x00R\vcertRenewalB\t\n" +
	"\apayload\"j\n" +
	"\fConfigIntent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"config_hcl\x18\x02 \x01(\fR\tconfigHcl\x12!\n" +
	"\fmerge_fields\x18\x03 \x03(\tR\vmergeFields\"h\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\x03R\rconfigVersion\"G\n" +
	"\x0eTelemetryBatch\x125\n" +
	"\x06events\x18\x01 \x03(\v2\x1d.flywall.cloud.TelemetryEventR\x06events\"g\n" +
	"\x0eTelemetryEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"U\n" +
	"\tConfigAck\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"k\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x9c\x01\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x124\n" +
	"\x04args\x18\x03 \x03(\v2 .flywall.cloud.Command.ArgsEntryR\x04args\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"6\n" +
	"\x12CertificateRenewal\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\"X\n" +
	"\x10GetConfigRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\x03R\x0ecurrentVersion\"f\n" +
	"\x11GetConfigResponse\x123\n" +
	"\x06config\x18\x01 \x01(\v2\x1b.flywall.cloud.ConfigIntentR\x06config\x12\x1c\n" +
	"\n" +
	"up_to_date\x18\x02 \x01(\bR\bupToDate2\xef\x01\n" +
	"\rDeviceService\x12E\n" +
	"\x06Enroll\x12\x1c.flywall.cloud.EnrollRequest\x1a\x1d.flywall.cloud.EnrollResponse\x12G\n" +
	"\aConnect\x12\x1b.flywall.cloud.AgentMessage\x1a\x1b.flywall.cloud.CloudMessage(\x010\x01\x12N\n" +
	"\tGetConfig\x12\x1f.flywall.cloud.GetConfigRequest\x1a .flywall.cloud.GetConfigResponseB\"Z grimm.is/flywall/api/cloud/protob\x06proto3"

var (
	file_device_proto_rawDescOnce sync.Once
	file_device_proto_rawDescData []byte
)

func file_device_proto_rawDescGZIP() []byte {
	file_device_proto_rawDescOnce.Do(func() {
		file_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_device_proto_rawDesc), len(file_device_proto_rawDesc)))
	})
	return file_device_proto_rawDescData
}

var file_device_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_device_proto_goTypes = []any{
	(*EnrollRequest)(nil),      // 0: flywall.cloud.EnrollRequest
	(*EnrollResponse)(nil),     // 1: flywall.cloud.EnrollResponse
	(*AgentMessage)(nil),       // 2: flywall.cloud.AgentMessage
	(*CloudMessage)(nil),       // 3: flywall.cloud.CloudMessage
	(*ConfigIntent)(nil),       // 4: flywall.cloud.ConfigIntent
	(*Heartbeat)(nil),          // 5: flywall.cloud.Heartbeat
	(*TelemetryBatch)(nil),     // 6: flywall.cloud.TelemetryBatch
	(*TelemetryEvent)(nil),     // 7: flywall.cloud.TelemetryEvent
	(*ConfigAck)(nil),          // 8: flywall.cloud.ConfigAck
	(*Alert)(nil),              // 9: flywall.cloud.Alert
	(*Command)(nil),            // 10: flywall.cloud.Command
	(*CertificateRenewal)(nil), // 11: flywall.cloud.CertificateRenewal
	(*GetConfigRequest)(nil),   // 12: flywall.cloud.GetConfigRequest
	(*GetConfigResponse)(nil),  // 13: flywall.cloud.GetConfigResponse
	nil,                        // 14: flywall.cloud.Command.ArgsEntry
}
var file_device_proto_depIdxs = []int32{
	5,  // 0: flywall.cloud.AgentMessage.heartbeat:type_name -> flywall.cloud.Heartbeat
	6,  // 1: flywall.cloud.AgentMessage.telemetry:type_name -> flywall.cloud.TelemetryBatch
	8,  // 2: flywall.cloud.AgentMessage.config_ack:type_name -> flywall.cloud.ConfigAck
	9,  // 3: flywall.cloud.AgentMessage.alert:type_name -> flywall.cloud.Alert
	4,  // 4: flywall.cloud.CloudMessage.config:type_name -> flywall.cloud.ConfigIntent
	10, // 5: flywall.cloud.CloudMessage.command:type_name -> flywall.cloud.Command
	11, // 6: flywall.cloud.CloudMessage.cert_renewal:type_name -> flywall.cloud.CertificateRenewal
	7,  // 7: flywall.cloud.TelemetryBatch.events:type_name -> flywall.cloud.TelemetryEvent
	14, // 8: flywall.cloud.Command.args:type_name -> flywall.cloud.Command.ArgsEntry
	4,  // 9: flywall.cloud.GetConfigResponse.config:type_name -> flywall.cloud.ConfigIntent
	0,  // 10: flywall.cloud.DeviceService.Enroll:input_type -> flywall.cloud.EnrollRequest
	2,  // 11: flywall.cloud.DeviceService.Connect:input_type -> flywall.cloud.AgentMessage
	12, // 12: flywall.cloud.DeviceService.GetConfig:input_type -> flywall.cloud.GetConfigRequest
	1,  // 13: flywall.cloud.DeviceService.Enroll:output_type -> flywall.cloud.EnrollResponse
	3,  // 14: flywall.cloud.DeviceService.Connect:output_type -> flywall.cloud.CloudMessage
	13, // 15: flywall.cloud.DeviceService.GetConfig:output_type -> flywall.cloud.GetConfigResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_device_proto_init() }
func file_device_proto_init() {
	if File_device_proto != nil {
		return
	}
	file_device_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Telemetry)(nil),
		(*AgentMessage_ConfigAck)(nil),
		(*AgentMessage_Alert)(nil),
	}
	file_device_proto_msgTypes[3].OneofWrappers = []any{
		(*CloudMessage_Config)(nil),
		(*CloudMessage_Command)(nil),
		(*CloudMessage_CertRenewal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_device_proto_rawDesc), len(file_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_proto_goTypes,
		DependencyIndexes: file_device_proto_depIdxs,
		MessageInfos:      file_device_proto_msgTypes,
	}.Build()
	File_device_proto = out.File
	file_device_proto_goTypes = nil
	file_device_proto_depIdxs = nil
}
