// Copyright (C) 2026 Ben Grimm. Licensed under AGPL-3.0 (https://www.gnu.org/licenses/agpl-3.0.txt)

// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package i18n

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de": &dictionary{index: deIndex, data: deData},
		"en": &dictionary{index: enIndex, data: enData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"\nError: Daemon exited immediately.\n":                             134,
	"          firewall config delete interface eth0\n":                 50,
	"          firewall config delete policy \"allow ssh\" (by name)\n": 52,
	"          firewall config delete policy lan wan\n":                 51,
	"  %-10s %-6s %-8s %s\n":                                            144,
	"  %-12s %s\n":                                                      142,
	"  %s\n":                                                            136,
	"  1. Start the firewall:  %s start\n":                              126,
	"  2. Access the UI:       https://%s/\n":                           127,
	"  Allowed IPs: %v\n":                                               8,
	"  Expires:     %s\n":                                               7,
	"  ID:          %s\n":                                               3,
	"  Name:        %s\n":                                               4,
	"  Permissions: %v\n":                                               6,
	"  Prefix:      %s\n":                                               5,
	"  Rate Limit:  %d req/min\n":                                       9,
	"  curl -H \"Authorization: Bearer %s\" http://localhost:8080/api/...\n": 10,
	"  curl -H \"X-API-Key: %s\" http://localhost:8080/api/...\n":            11,
	" with labels %v":                    54,
	"%-20s %-12s %-12s %-10d %-15s %s\n": 86,
	"%-20s %-12s %-12s %-10s %-15s %s\n": 85,
	"%s":                                 29,
	"%s\t%d\t%s\t%s\t%s\t%s\n":           22,
	"%s\t%s\t%d\n":                       24,
	"%s\t%s\n":                           23,
	"%s API Key Management\n\nUsage:\n  %s apikey <command> [options]\n\nCommands:\n  generate    Generate a new API key\n  list        List all API keys\n  revoke      Revoke an API key\n  help        Show this help\n\nGenerate Options:\n  --name <name>           Name for the key (required)\n  --permissions <perms>   Comma-separated permissions (required)\n  --expires <duration>    Expiration (e.g., \"24h\", \"7d\", \"30d\")\n  --allowed-ips <ips>     Comma-separated allowed IPs\n  --rate-limit <rpm>      Requests per minute limit\n  --description <desc>    Description\n  --json, -j              Output in JSON format (for scripting)\n\nPermission Values:\n  Read:   config:read, uplinks:read, firewall:read, dhcp:read, dns:read,\n          learning:read, metrics:read, health:read, logs:read, read:*\n  Write:  config:write, uplinks:write, firewall:write, dhcp:write,\n          dns:write, learning:write, write:*\n  Admin:  admin:keys, admin:system, admin:backup, admin:*\n  All:    * (full access)\n\nPreset Permissions:\n  --preset readonly       Read-only access to all resources\n  --preset uplink         Uplink management (read/write uplinks, read health)\n  --preset monitoring     Metrics, health, and logs (read-only)\n  --preset admin          Full administrative access\n\nExamples:\n  # Generate a read-only key\n  %s apikey generate --name \"monitoring\" --preset readonly\n\n  # Generate an uplink control key for your script\n  %s apikey generate --name \"vpn-switcher\" --preset uplink --expires 365d\n\n  # Generate a full admin key\n  %s apikey generate --name \"admin-key\" --preset admin\n\n  # Generate a key with specific permissions\n  %s apikey generate --name \"custom\" --permissions \"uplinks:read,uplinks:write\"\n\n  # Generate a key restricted to specific IPs\n  %s apikey generate --name \"local-only\" --preset admin --allowed-ips \"127.0.0.1,192.168.1.0/24\"\n\n": 1,
	"%s [%s] %s: %s\n":                                          113,
	"- %s\n":                                                    78,
	"? [y/N]: ":                                                 55,
	"API Key: %s\n":                                             2,
	"Admin already exists":                                      190,
	"Age:          %s\n":                                        97,
	"Apply this configuration? [y/N]: ":                         34,
	"Auth not configured":                                       187,
	"Backup created: version %d\n":                              37,
	"CIDR is required":                                          183,
	"Cache Dir:    %s\n":                                        107,
	"Cached Lists: %d\n":                                        105,
	"Cannot delete admin user":                                  195,
	"Canonicalization failed: %v\n":                             61,
	"Capture is currently running. Stop it first.":              164,
	"Certificate not found":                                     199,
	"Clock anchor loaded: %s\n":                                 68,
	"Collector not initialized":                                 176,
	"Config:  %s\n":                                             140,
	"Configuration not loaded":                                  162,
	"Configuration valid!\n":                                    14,
	"Configuration validation failed: %v\n":                     33,
	"Configuration written to %s\n":                             77,
	"Connected to %s\n":                                         109,
	"Control Plane Disconnected":                                185,
	"Control plane client not connected":                        154,
	"Control plane not connected":                               151,
	"Delete %s":                                                 53,
	"Device MAC or ID is required":                              166,
	"Editor failed: %v\n":                                       44,
	"Entries:      %d\n":                                        95,
	"Error applying configuration: %s\n":                        39,
	"Error deleting section: %s\n":                              57,
	"Error generating firewall rules: %v\n":                     20,
	"Error initializing firewall manager: %v\n":                 21,
	"Error parsing backup: %v\n":                                74,
	"Error polling logs: %v\n":                                  112,
	"Error reading config dir: %v\n":                            129,
	"Error running console: %v\n":                               67,
	"Error writing config: %v\n":                                76,
	"Error: %v\n":                                               13,
	"Error: --api-key is required for remote connection\n":      66,
	"Error: --input is required\n":                              71,
	"Error: API server returned status %d\n":                    81,
	"Error: Cache command is required\n":                        101,
	"Error: Failed to connect to API server: %v\n":              80,
	"Error: Failed to create request: %v\n":                     108,
	"Error: Failed to parse response: %v\n":                     83,
	"Error: Failed to read response: %v\n":                      82,
	"Error: IPSet '%s' not found\n":                             89,
	"Error: IPSet name is required\n":                           87,
	"Error: reset must run as root\n":                           128,
	"Error: setup must run as root\n":                           122,
	"Error: unsupported type '%s'\n":                            72,
	"Examples: firewall config delete dhcp\n":                   49,
	"Failed to apply configuration: %v\n":                       47,
	"Failed to clone config":                                    156,
	"Failed to connect to control plane: %v\n":                  26,
	"Failed to create temporary file: %v\n":                     42,
	"Failed to delete section: %v\n":                            56,
	"Failed to determine executable path: %v\n":                 114,
	"Failed to enable debug logging: %v\n":                      65,
	"Failed to generate HCL: %v\n":                              62,
	"Failed to get configuration: %v\n":                         28,
	"Failed to get status: %v\n":                                138,
	"Failed to initialize auth":                                 192,
	"Failed to load config file: %v\n":                          59,
	"Failed to read config file: %v\n":                          31,
	"Failed to read edited file: %v\n":                          45,
	"Failed to read from stdin: %v\n":                           32,
	"Failed to read request body":                               157,
	"Failed to save migrated config: %v\n":                      63,
	"Failed to set configuration: %v\n":                         38,
	"Failed to write temporary file: %v\n":                      43,
	"Found: %d interfaces, %d filter rules, %d NAT rules\n":     75,
	"IP address is required":                                    184,
	"IPSet Cache Information:\n\n":                              104,
	"IPSet Details:\n\n":                                        90,
	"IPSets (%d total):\n\n":                                    84,
	"Interface is required":                                     163,
	"Interface name required":                                   174,
	"Interfaces: %d\n":                                          16,
	"Invalid DNS configuration format":                          158,
	"Invalid credentials":                                       188,
	"Invalid dst_ip":                                            161,
	"Invalid group ID":                                          173,
	"Invalid output format: %s\n":                               30,
	"Invalid request body":                                      152,
	"Invalid src_ip":                                            160,
	"Invalid version":                                           149,
	"Is the daemon running? Start with: flywall ctl <config>\n": 137,
	"Key %s revoked.\n":                                         12,
	"Last Update:  %s\n":                                        96,
	"Log output:\n":                                             135,
	"Logs: %s\n":                                                133,
	"MAC address is required":                                   198,
	"MAC and IdentityID are required":                           167,
	"MAC is required":                                           168,
	"Make sure 'firewall ctl' is running first.\n":              27,
	"Method not allowed":                                        146,
	"Migration failed: %v\n":                                    60,
	"Migration: %s -> %s\n":                                     19,
	"Missing 'arch' field":                                      197,
	"Missing 'checksum' field":                                  196,
	"Missing group ID":                                          172,
	"Monitor: Child crashed with exit code %d (err: %v). Restarting...\n":      118,
	"Monitor: Detected crash loop (%d fast crashes). Backing off for 30s...\n": 119,
	"Monitor: Failed to start child: %v\n":                                     115,
	"Monitor: Forwarding signal %v to child...\n":                              117,
	"Monitor: Started flywall ctl (pid=%d)\n":                                  116,
	"Name:         %s\n":                               91,
	"Next Update:  %s\n":                               98,
	"No capture file found":                            165,
	"Options: [r]etry, [a]bort, [e]dit again: ":        46,
	"Page not found":                                   200,
	"Parsed backup file: %s (Type: %s)\n":              73,
	"Policies: %d\n":                                   18,
	"Policy not found":                                 178,
	"Rate limit exceeded for batch":                    170,
	"Rule not found":                                   181,
	"Schema Version: %s\n":                             15,
	"Section type required (use ?type=dhcp)":           171,
	"Sending SIGHUP to process %d...\n":                121,
	"Server Certificate Fingerprint: %s\n":             110,
	"Setup failed: %v\n":                               123,
	"Source URL:   %s\n":                               94,
	"Source:       %s\n":                               93,
	"Started %s (PID: %d)\n":                           132,
	"Stopping %s (PID: %d)...\n":                       145,
	"Successfully deleted %s":                          58,
	"Successfully migrated %s to schema version %s\n":  64,
	"Task ID required":                                 153,
	"Task not found":                                   155,
	"To pin this certificate, use --fingerprint %s\n":  111,
	"Too many login attempts. Please try again later.": 186,
	"Too many requests in batch":                       169,
	"Too many setup attempts. Please try again later.": 189,
	"Total Size:   %d bytes\n":                         106,
	"Type:         %s\n":                               92,
	"Unknown cache command: %s\n":                      103,
	"Unknown config command: %s\n\n":                   25,
	"Unknown ipset command: %s\n\n":                    79,
	"Uptime:  %s\n":                                    139,
	"Usage: firewall config delete <section-type> [label1] [label2]...\n":         48,
	"Usage: firewall ipset cache <info|clear>\n":                                  102,
	"Usage: firewall ipset refresh <name>\n":                                      100,
	"Usage: firewall ipset show <name>\n":                                         88,
	"Usage: firewall ipset update <name>\n":                                       99,
	"User not found":                                                              194,
	"Username and password required":                                              191,
	"Username required":                                                           193,
	"Validating configuration: %s\n":                                              120,
	"Validation failed: %v\n":                                                     41,
	"Version is required":                                                         147,
	"Version parameter required":                                                  148,
	"Waiting for previous API instance to release lock... (%d/%d)\n":              0,
	"Warning: Failed to create backup: %s\n":                                      36,
	"Warning: Failed to create backup: %v\n":                                      35,
	"Warning: Failed to get interfaces: %v\n":                                     143,
	"Warning: Failed to get services: %v\n":                                       141,
	"Warning: Removing stale PID file %s\n":                                       131,
	"Warning: System time (%s) appears unreasonable and no anchor file exists.\n": 70,
	"Warning: System time (%s) appears unreasonable. Last known good time was %s. Waiting for NTP sync.\n": 69,
	"Warning: failed to create admin user: %v\n":                                                           125,
	"Warning: failed to initialize auth: %v\n":                                                             124,
	"Warning: failed to remove %s: %v\n":                                                                   130,
	"You can restore from backup version %d if needed\n":                                                   40,
	"Zones: %d\n":                              17,
	"max_backups must be at least 1":           150,
	"name parameter required":                  175,
	"policy_name and relative_to are required": 177,
	"policy_name is required":                  179,
	"rule_name and relative_to are required":   180,
	"runtime service not available":            182,
	"src_ip and dst_ip are required":           159,
}

var deIndex = []uint32{ // 202 elements
	// Entry 0 - 1F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 20 - 3F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 40 - 5F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 60 - 7F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 80 - 9F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry A0 - BF
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry C0 - DF
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000,
} // Size: 832 bytes

const deData string = ""

var enIndex = []uint32{ // 202 elements
	// Entry 0 - 1F
	0x00000000, 0x00000048, 0x00000789, 0x0000079d,
	0x000007b7, 0x000007d1, 0x000007eb, 0x00000805,
	0x0000081f, 0x00000839, 0x0000085b, 0x000008a6,
	0x000008e6, 0x000008fe, 0x00000910, 0x0000092a,
	0x00000945, 0x0000095c, 0x0000096e, 0x00000983,
	0x000009a2, 0x000009ce, 0x000009fe, 0x00000a27,
	0x00000a38, 0x00000a4f, 0x00000a73, 0x00000aa2,
	0x00000ad2, 0x00000afa, 0x00000b00, 0x00000b22,
	// Entry 20 - 3F
	0x00000b49, 0x00000b6f, 0x00000b9b, 0x00000bc1,
	0x00000bee, 0x00000c1b, 0x00000c3e, 0x00000c66,
	0x00000c8f, 0x00000cc8, 0x00000ce6, 0x00000d12,
	0x00000d3d, 0x00000d57, 0x00000d7e, 0x00000dac,
	0x00000dd6, 0x00000e1d, 0x00000e48, 0x00000e7d,
	0x00000eb2, 0x00000ef5, 0x00000f02, 0x00000f19,
	0x00000f27, 0x00000f4c, 0x00000f6f, 0x00000f8a,
	0x00000fb1, 0x00000fce, 0x00000ff2, 0x00001015,
	// Entry 40 - 5F
	0x00001040, 0x00001079, 0x000010a4, 0x000010dc,
	0x000010fe, 0x0000111e, 0x0000118c, 0x000011de,
	0x000011fe, 0x00001223, 0x00001250, 0x00001271,
	0x000012b3, 0x000012d4, 0x000012f8, 0x00001305,
	0x00001328, 0x0000135b, 0x00001388, 0x000013b3,
	0x000013df, 0x000013fb, 0x00001433, 0x0000146b,
	0x0000148e, 0x000014b5, 0x000014d9, 0x000014ee,
	0x00001507, 0x00001520, 0x00001539, 0x00001552,
	// Entry 60 - 7F
	0x0000156b, 0x00001584, 0x0000159d, 0x000015b6,
	0x000015df, 0x00001609, 0x0000162f, 0x0000165d,
	0x0000167f, 0x0000169e, 0x000016b7, 0x000016d6,
	0x000016ef, 0x0000171b, 0x00001733, 0x0000175e,
	0x00001794, 0x000017b3, 0x000017d3, 0x00001803,
	0x0000182e, 0x0000185c, 0x0000188e, 0x000018db,
	0x0000192a, 0x0000194f, 0x00001977, 0x0000199a,
	0x000019b3, 0x000019e2, 0x00001a13, 0x00001a3e,
	// Entry 80 - 9F
	0x00001a6c, 0x00001a8f, 0x00001ab4, 0x00001ae0,
	0x00001b0c, 0x00001b2c, 0x00001b3d, 0x00001b65,
	0x00001b76, 0x00001b83, 0x00001bc0, 0x00001be1,
	0x00001bf5, 0x00001c09, 0x00001c35, 0x00001c4b,
	0x00001c79, 0x00001c9f, 0x00001cc3, 0x00001cd6,
	0x00001cea, 0x00001d05, 0x00001d15, 0x00001d34,
	0x00001d50, 0x00001d65, 0x00001d76, 0x00001d99,
	0x00001da8, 0x00001dbf, 0x00001ddb, 0x00001dfc,
	// Entry A0 - BF
	0x00001e1b, 0x00001e2a, 0x00001e39, 0x00001e52,
	0x00001e68, 0x00001e95, 0x00001eab, 0x00001ec8,
	0x00001ee8, 0x00001ef8, 0x00001f13, 0x00001f31,
	0x00001f58, 0x00001f69, 0x00001f7a, 0x00001f92,
	0x00001faa, 0x00001fc4, 0x00001fed, 0x00001ffe,
	0x00002016, 0x0000203d, 0x0000204c, 0x0000206a,
	0x0000207b, 0x00002092, 0x000020ad, 0x000020de,
	0x000020f2, 0x00002106, 0x00002137, 0x0000214c,
	// Entry C0 - DF
	0x0000216b, 0x00002185, 0x00002197, 0x000021a6,
	0x000021bf, 0x000021d8, 0x000021ed, 0x00002205,
	0x0000221b, 0x0000222a,
} // Size: 832 bytes

const enData string = "" + // Size: 8746 bytes
	"\x04\x00\x01\x0aC\x02Waiting for previous API instance to release lock.." +
	". (%[1]d/%[2]d)\x04\x00\x02\x0a\x0a\xba\x0e\x02%[1]s API Key Management" +
	"\x0a\x0aUsage:\x0a  %[2]s apikey <command> [options]\x0a\x0aCommands:" +
	"\x0a  generate    Generate a new API key\x0a  list        List all API k" +
	"eys\x0a  revoke      Revoke an API key\x0a  help        Show this help" +
	"\x0a\x0aGenerate Options:\x0a  --name <name>           Name for the key " +
	"(required)\x0a  --permissions <perms>   Comma-separated permissions (req" +
	"uired)\x0a  --expires <duration>    Expiration (e.g., \x2224h\x22, \x227" +
	"d\x22, \x2230d\x22)\x0a  --allowed-ips <ips>     Comma-separated allowed" +
	" IPs\x0a  --rate-limit <rpm>      Requests per minute limit\x0a  --descr" +
	"iption <desc>    Description\x0a  --json, -j              Output in JSON" +
	" format (for scripting)\x0a\x0aPermission Values:\x0a  Read:   config:re" +
	"ad, uplinks:read, firewall:read, dhcp:read, dns:read,\x0a          learn" +
	"ing:read, metrics:read, health:read, logs:read, read:*\x0a  Write:  conf" +
	"ig:write, uplinks:write, firewall:write, dhcp:write,\x0a          dns:wr" +
	"ite, learning:write, write:*\x0a  Admin:  admin:keys, admin:system, admi" +
	"n:backup, admin:*\x0a  All:    * (full access)\x0a\x0aPreset Permissions" +
	":\x0a  --preset readonly       Read-only access to all resources\x0a  --" +
	"preset uplink         Uplink management (read/write uplinks, read health" +
	")\x0a  --preset monitoring     Metrics, health, and logs (read-only)\x0a" +
	"  --preset admin          Full administrative access\x0a\x0aExamples:" +
	"\x0a  # Generate a read-only key\x0a  %[3]s apikey generate --name \x22m" +
	"onitoring\x22 --preset readonly\x0a\x0a  # Generate an uplink control ke" +
	"y for your script\x0a  %[4]s apikey generate --name \x22vpn-switcher\x22" +
	" --preset uplink --expires 365d\x0a\x0a  # Generate a full admin key\x0a" +
	"  %[5]s apikey generate --name \x22admin-key\x22 --preset admin\x0a\x0a " +
	" # Generate a key with specific permissions\x0a  %[6]s apikey generate -" +
	"-name \x22custom\x22 --permissions \x22uplinks:read,uplinks:write\x22" +
	"\x0a\x0a  # Generate a key restricted to specific IPs\x0a  %[7]s apikey " +
	"generate --name \x22local-only\x22 --preset admin --allowed-ips \x22127." +
	"0.0.1,192.168.1.0/24\x22\x04\x00\x01\x0a\x0f\x02API Key: %[1]s\x04\x02  " +
	"\x01\x0a\x13\x02ID:          %[1]s\x04\x02  \x01\x0a\x13\x02Name:       " +
	" %[1]s\x04\x02  \x01\x0a\x13\x02Prefix:      %[1]s\x04\x02  \x01\x0a\x13" +
	"\x02Permissions: %[1]v\x04\x02  \x01\x0a\x13\x02Expires:     %[1]s\x04" +
	"\x02  \x01\x0a\x13\x02Allowed IPs: %[1]v\x04\x02  \x01\x0a\x1b\x02Rate L" +
	"imit:  %[1]d req/min\x04\x02  \x01\x0aD\x02curl -H \x22Authorization: Be" +
	"arer %[1]s\x22 http://localhost:8080/api/...\x04\x02  \x01\x0a9\x02curl " +
	"-H \x22X-API-Key: %[1]s\x22 http://localhost:8080/api/...\x04\x00\x01" +
	"\x0a\x13\x02Key %[1]s revoked.\x04\x00\x01\x0a\x0d\x02Error: %[1]v\x04" +
	"\x00\x01\x0a\x15\x02Configuration valid!\x04\x00\x01\x0a\x16\x02Schema V" +
	"ersion: %[1]s\x04\x00\x01\x0a\x12\x02Interfaces: %[1]d\x04\x00\x01\x0a" +
	"\x0d\x02Zones: %[1]d\x04\x00\x01\x0a\x10\x02Policies: %[1]d\x04\x00\x01" +
	"\x0a\x1a\x02Migration: %[1]s -> %[2]s\x04\x00\x01\x0a'\x02Error generati" +
	"ng firewall rules: %[1]v\x04\x00\x01\x0a+\x02Error initializing firewall" +
	" manager: %[1]v\x04\x00\x01\x0a$\x02%[1]s\x09%[2]d\x09%[3]s\x09%[4]s\x09" +
	"%[5]s\x09%[6]s\x04\x00\x01\x0a\x0c\x02%[1]s\x09%[2]s\x04\x00\x01\x0a\x12" +
	"\x02%[1]s\x09%[2]s\x09%[3]d\x04\x00\x02\x0a\x0a\x1e\x02Unknown config co" +
	"mmand: %[1]s\x04\x00\x01\x0a*\x02Failed to connect to control plane: %[1" +
	"]v\x04\x00\x01\x0a+\x02Make sure 'firewall ctl' is running first.\x04" +
	"\x00\x01\x0a#\x02Failed to get configuration: %[1]v\x02%[1]s\x04\x00\x01" +
	"\x0a\x1d\x02Invalid output format: %[1]s\x04\x00\x01\x0a\x22\x02Failed t" +
	"o read config file: %[1]v\x04\x00\x01\x0a!\x02Failed to read from stdin:" +
	" %[1]v\x04\x00\x01\x0a'\x02Configuration validation failed: %[1]v\x04" +
	"\x00\x01 !\x02Apply this configuration? [y/N]:\x04\x00\x01\x0a(\x02Warni" +
	"ng: Failed to create backup: %[1]v\x04\x00\x01\x0a(\x02Warning: Failed t" +
	"o create backup: %[1]s\x04\x00\x01\x0a\x1e\x02Backup created: version %[" +
	"1]d\x04\x00\x01\x0a#\x02Failed to set configuration: %[1]v\x04\x00\x01" +
	"\x0a$\x02Error applying configuration: %[1]s\x04\x00\x01\x0a4\x02You can" +
	" restore from backup version %[1]d if needed\x04\x00\x01\x0a\x19\x02Vali" +
	"dation failed: %[1]v\x04\x00\x01\x0a'\x02Failed to create temporary file" +
	": %[1]v\x04\x00\x01\x0a&\x02Failed to write temporary file: %[1]v\x04" +
	"\x00\x01\x0a\x15\x02Editor failed: %[1]v\x04\x00\x01\x0a\x22\x02Failed t" +
	"o read edited file: %[1]v\x04\x00\x01 )\x02Options: [r]etry, [a]bort, [e" +
	"]dit again:\x04\x00\x01\x0a%\x02Failed to apply configuration: %[1]v\x04" +
	"\x00\x01\x0aB\x02Usage: firewall config delete <section-type> [label1] [" +
	"label2]...\x04\x00\x01\x0a&\x02Examples: firewall config delete dhcp\x04" +
	"\x0a          \x01\x0a&\x02firewall config delete interface eth0\x04\x0a" +
	"          \x01\x0a&\x02firewall config delete policy lan wan\x04\x0a    " +
	"      \x01\x0a4\x02firewall config delete policy \x22allow ssh\x22 (by n" +
	"ame)\x02Delete %[1]s\x04\x01 \x00\x12\x02with labels %[1]v\x04\x00\x01 " +
	"\x09\x02? [y/N]:\x04\x00\x01\x0a \x02Failed to delete section: %[1]v\x04" +
	"\x00\x01\x0a\x1e\x02Error deleting section: %[1]s\x02Successfully delete" +
	"d %[1]s\x04\x00\x01\x0a\x22\x02Failed to load config file: %[1]v\x04\x00" +
	"\x01\x0a\x18\x02Migration failed: %[1]v\x04\x00\x01\x0a\x1f\x02Canonical" +
	"ization failed: %[1]v\x04\x00\x01\x0a\x1e\x02Failed to generate HCL: %[1" +
	"]v\x04\x00\x01\x0a&\x02Failed to save migrated config: %[1]v\x04\x00\x01" +
	"\x0a4\x02Successfully migrated %[1]s to schema version %[2]s\x04\x00\x01" +
	"\x0a&\x02Failed to enable debug logging: %[1]v\x04\x00\x01\x0a3\x02Error" +
	": --api-key is required for remote connection\x04\x00\x01\x0a\x1d\x02Err" +
	"or running console: %[1]v\x04\x00\x01\x0a\x1b\x02Clock anchor loaded: %[" +
	"1]s\x04\x00\x01\x0ai\x02Warning: System time (%[1]s) appears unreasonabl" +
	"e. Last known good time was %[2]s. Waiting for NTP sync.\x04\x00\x01\x0a" +
	"M\x02Warning: System time (%[1]s) appears unreasonable and no anchor fil" +
	"e exists.\x04\x00\x01\x0a\x1b\x02Error: --input is required\x04\x00\x01" +
	"\x0a \x02Error: unsupported type '%[1]s'\x04\x00\x01\x0a(\x02Parsed back" +
	"up file: %[1]s (Type: %[2]s)\x04\x00\x01\x0a\x1c\x02Error parsing backup" +
	": %[1]v\x04\x00\x01\x0a=\x02Found: %[1]d interfaces, %[2]d filter rules," +
	" %[3]d NAT rules\x04\x00\x01\x0a\x1c\x02Error writing config: %[1]v\x04" +
	"\x00\x01\x0a\x1f\x02Configuration written to %[1]s\x04\x00\x01\x0a\x08" +
	"\x02- %[1]s\x04\x00\x02\x0a\x0a\x1d\x02Unknown ipset command: %[1]s\x04" +
	"\x00\x01\x0a.\x02Error: Failed to connect to API server: %[1]v\x04\x00" +
	"\x01\x0a(\x02Error: API server returned status %[1]d\x04\x00\x01\x0a&" +
	"\x02Error: Failed to read response: %[1]v\x04\x00\x01\x0a'\x02Error: Fai" +
	"led to parse response: %[1]v\x04\x00\x02\x0a\x0a\x16\x02IPSets (%[1]d to" +
	"tal):\x04\x00\x01\x0a3\x02%-20[1]s %-12[2]s %-12[3]s %-10[4]s %-15[5]s %" +
	"[6]s\x04\x00\x01\x0a3\x02%-20[1]s %-12[2]s %-12[3]s %-10[4]d %-15[5]s %[" +
	"6]s\x04\x00\x01\x0a\x1e\x02Error: IPSet name is required\x04\x00\x01\x0a" +
	"\x22\x02Usage: firewall ipset show <name>\x04\x00\x01\x0a\x1f\x02Error: " +
	"IPSet '%[1]s' not found\x04\x00\x02\x0a\x0a\x0f\x02IPSet Details:\x04" +
	"\x00\x01\x0a\x14\x02Name:         %[1]s\x04\x00\x01\x0a\x14\x02Type:    " +
	"     %[1]s\x04\x00\x01\x0a\x14\x02Source:       %[1]s\x04\x00\x01\x0a" +
	"\x14\x02Source URL:   %[1]s\x04\x00\x01\x0a\x14\x02Entries:      %[1]d" +
	"\x04\x00\x01\x0a\x14\x02Last Update:  %[1]s\x04\x00\x01\x0a\x14\x02Age: " +
	"         %[1]s\x04\x00\x01\x0a\x14\x02Next Update:  %[1]s\x04\x00\x01" +
	"\x0a$\x02Usage: firewall ipset update <name>\x04\x00\x01\x0a%\x02Usage: " +
	"firewall ipset refresh <name>\x04\x00\x01\x0a!\x02Error: Cache command i" +
	"s required\x04\x00\x01\x0a)\x02Usage: firewall ipset cache <info|clear>" +
	"\x04\x00\x01\x0a\x1d\x02Unknown cache command: %[1]s\x04\x00\x02\x0a\x0a" +
	"\x19\x02IPSet Cache Information:\x04\x00\x01\x0a\x14\x02Cached Lists: %[" +
	"1]d\x04\x00\x01\x0a\x1a\x02Total Size:   %[1]d bytes\x04\x00\x01\x0a\x14" +
	"\x02Cache Dir:    %[1]s\x04\x00\x01\x0a'\x02Error: Failed to create requ" +
	"est: %[1]v\x04\x00\x01\x0a\x13\x02Connected to %[1]s\x04\x00\x01\x0a&" +
	"\x02Server Certificate Fingerprint: %[1]s\x04\x00\x01\x0a1\x02To pin thi" +
	"s certificate, use --fingerprint %[1]s\x04\x00\x01\x0a\x1a\x02Error poll" +
	"ing logs: %[1]v\x04\x00\x01\x0a\x1b\x02%[1]s [%[2]s] %[3]s: %[4]s\x04" +
	"\x00\x01\x0a+\x02Failed to determine executable path: %[1]v\x04\x00\x01" +
	"\x0a&\x02Monitor: Failed to start child: %[1]v\x04\x00\x01\x0a)\x02Monit" +
	"or: Started flywall ctl (pid=%[1]d)\x04\x00\x01\x0a-\x02Monitor: Forward" +
	"ing signal %[1]v to child...\x04\x00\x01\x0aH\x02Monitor: Child crashed " +
	"with exit code %[1]d (err: %[2]v). Restarting...\x04\x00\x01\x0aJ\x02Mon" +
	"itor: Detected crash loop (%[1]d fast crashes). Backing off for 30s..." +
	"\x04\x00\x01\x0a \x02Validating configuration: %[1]s\x04\x00\x01\x0a#" +
	"\x02Sending SIGHUP to process %[1]d...\x04\x00\x01\x0a\x1e\x02Error: set" +
	"up must run as root\x04\x00\x01\x0a\x14\x02Setup failed: %[1]v\x04\x00" +
	"\x01\x0a*\x02Warning: failed to initialize auth: %[1]v\x04\x00\x01\x0a," +
	"\x02Warning: failed to create admin user: %[1]v\x04\x02  \x01\x0a$\x021." +
	" Start the firewall:  %[1]s start\x04\x02  \x01\x0a'\x022. Access the UI" +
	":       https://%[1]s/\x04\x00\x01\x0a\x1e\x02Error: reset must run as r" +
	"oot\x04\x00\x01\x0a \x02Error reading config dir: %[1]v\x04\x00\x01\x0a'" +
	"\x02Warning: failed to remove %[1]s: %[2]v\x04\x00\x01\x0a'\x02Warning: " +
	"Removing stale PID file %[1]s\x04\x00\x01\x0a\x1b\x02Started %[1]s (PID:" +
	" %[2]d)\x04\x00\x01\x0a\x0c\x02Logs: %[1]s\x04\x01\x0a\x01\x0a\x22\x02Er" +
	"ror: Daemon exited immediately.\x04\x00\x01\x0a\x0c\x02Log output:\x04" +
	"\x02  \x01\x0a\x06\x02%[1]s\x04\x00\x01\x0a8\x02Is the daemon running? S" +
	"tart with: flywall ctl <config>\x04\x00\x01\x0a\x1c\x02Failed to get sta" +
	"tus: %[1]v\x04\x00\x01\x0a\x0f\x02Uptime:  %[1]s\x04\x00\x01\x0a\x0f\x02" +
	"Config:  %[1]s\x04\x00\x01\x0a'\x02Warning: Failed to get services: %[1]" +
	"v\x04\x02  \x01\x0a\x0f\x02%-12[1]s %[2]s\x04\x00\x01\x0a)\x02Warning: F" +
	"ailed to get interfaces: %[1]v\x04\x02  \x01\x0a\x1f\x02%-10[1]s %-6[2]s" +
	" %-8[3]s %[4]s\x04\x00\x01\x0a\x1f\x02Stopping %[1]s (PID: %[2]d)...\x02" +
	"Method not allowed\x02Version is required\x02Version parameter required" +
	"\x02Invalid version\x02max_backups must be at least 1\x02Control plane n" +
	"ot connected\x02Invalid request body\x02Task ID required\x02Control plan" +
	"e client not connected\x02Task not found\x02Failed to clone config\x02Fa" +
	"iled to read request body\x02Invalid DNS configuration format\x02src_ip " +
	"and dst_ip are required\x02Invalid src_ip\x02Invalid dst_ip\x02Configura" +
	"tion not loaded\x02Interface is required\x02Capture is currently running" +
	". Stop it first.\x02No capture file found\x02Device MAC or ID is require" +
	"d\x02MAC and IdentityID are required\x02MAC is required\x02Too many requ" +
	"ests in batch\x02Rate limit exceeded for batch\x02Section type required " +
	"(use ?type=dhcp)\x02Missing group ID\x02Invalid group ID\x02Interface na" +
	"me required\x02name parameter required\x02Collector not initialized\x02p" +
	"olicy_name and relative_to are required\x02Policy not found\x02policy_na" +
	"me is required\x02rule_name and relative_to are required\x02Rule not fou" +
	"nd\x02runtime service not available\x02CIDR is required\x02IP address is" +
	" required\x02Control Plane Disconnected\x02Too many login attempts. Plea" +
	"se try again later.\x02Auth not configured\x02Invalid credentials\x02Too" +
	" many setup attempts. Please try again later.\x02Admin already exists" +
	"\x02Username and password required\x02Failed to initialize auth\x02Usern" +
	"ame required\x02User not found\x02Cannot delete admin user\x02Missing 'c" +
	"hecksum' field\x02Missing 'arch' field\x02MAC address is required\x02Cer" +
	"tificate not found\x02Page not found"

	// Total table size 10410 bytes (10KiB); checksum: 95FD8AD8
